import type { NextPage } from 'next';
import Head from 'next/head';
import DetailsScreen from '../components/DetailsScreen';
import Sidebar from '../components/Sidebar';
import { useState } from 'react';

const Home: NextPage = () => {
  const [product, setProduct] = useState<string>('');
  const [state, setState] = useState<string>('');
  const [city, setCity] = useState<string>('');
  console.log(product, state, city);
  return (
    <div className="bg-[#292929] h-screen w-screen  ">
      <Head>
        <title>Edvora Test</title>
        <meta
          name="description"
          content="Generated by create next app"
        />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-full pt-[43px]">
        <div className="w-3/12">
          <Sidebar
            setProduct={setProduct}
            setState={setState}
            setCity={setCity}
            product={product}
            state={state}
            city={city}
          />
        </div>
        <div className="w-9/12">
          <DetailsScreen
            product={product}
            state={state}
            city={city}
          />
        </div>
      </div>
    </div>
  );
};

export default Home;
